---
title: "Research - McConnell"
---

<font size = 3>

## Collocation & individual differences in statistical language processing
Coming (hopefully) soon!

## Collocation measures, task effects & chunk frequency
In the paper [Effects of task and corpus-derived association scores on the online processing of collocations](https://www.degruyter.com/view/j/cllt.ahead-of-print/cllt-2018-0030/cllt-2018-0030.xml), [Alice Blumenthal-Dramé](https://www.anglistik.uni-freiburg.de/seminar/mitarbeiter-und-sprechstunden/blumenthal) and I investigate multiple measures of statistical association to address if and how corpus data can reflect language processing mechanisms in the mind. In this, we also look at the processing of chunks (modifier-noun bigrams) and their internal constituents in parallel. All this is done across two task conditions, to test if a minimal task difference can affect the relationship between these measures and reading times. You can see the [poster version here](https://www.researchgate.net/profile/Kyla_Mcconnell2/publication/335991813_Can_corpus-derived_collocation_measures_reflect_expectations_in_language_processing/links/5d89d584458515cbd1be541c/Can-corpus-derived-collocation-measures-reflect-expectations-in-language-processing.pdf). A short and simple summary for general audiences can be found [here](https://kyla-mcconnell.github.io/website/collocations.html).

</font>