---
title: "Stats Group Freiburg"
---

<font size = 3>

#Statistics Group for Linguists, Freiburg

##Who are we?
As the use of sophisticated statistical methods quickly becomes ubiquitous in the social and language sciences, the interest in learning and refining quantitative methods is spreading through all levels of linguistic research and study. Introductory courses in statistics and research design are becoming part of many M.A. and even B.A. curriculums; however, self-study of advanced topics and applying theoretical concepts to one’s own data can be challenging. To share our enthusiasm for quantitative methods and to grow a community of researchers interested in improving their statistical skills, I founded the Statistics Group for Linguists in Freiburg together with my colleague Julia Müller in May 2019.

We're a peer support group consisting of early career researchers and advanced graduate students who meet up every other week to learn and practice statistics together. After reading up on a topic in a book or online resource, we discuss and go through exercises together in the statistical programming language ‘R’. 

As of August 2020, we’ve covered data wrangling with dplyr, visualization with ggplot, fundamental statistical concepts like correlation, regression, t-tests, and ANOVAs, as well as mixed effects modeling and best practices in fitting linear and non-linear models. Looking forward, our upcominng topics include advanced methods like decision trees, random forests, principle component analysis (PCA), cluster analysis and neural networks. 

##Resources

Check out my [Github repository](https://github.com/kyla-mcconnell/R_stats) for our current collection of resources. They consist of both exercises and notes, many of which draw heavily from our favorite statistical resources:

[R for Data Science, Hadley Wickham & Garrett Grolemund](https://r4ds.had.co.nz)
[Discovering Statistics with R, Andy Field](https://www.amazon.com/Discovering-Statistics-Using-Andy-Field/dp/1446200469/ref=sr_1_1?crid=CKZWXG1OAWRX&keywords=discovering+statistics+using+r&qid=1574011921&sprefix=discovering+stat%2Caps%2C230&sr=8-1)
[Data Skills tutorial, Dale Barr and Lisa DeBruine](https://gupsych.github.io/data_skills/01_intro.html)
[Statistics for Linguists, Bodo Winter](https://www.crcpress.com/Statistics-for-Linguists-An-Introduction-Using-R/Winter/p/book/9781138056091)
[How to do Linguistics with R, Natalia Levshina](https://benjamins.com/sites/z.195/)

</font>